no more mac ci

diff --git a/.github/actions/setup/action.yml b/.github/actions/setup/action.yml
--- a/.github/actions/setup/action.yml
+++ b/.github/actions/setup/action.yml
@@ -1,3 +1,5 @@
+# Note: this is only compatible with Linux runners.
+
 name: Test setup
 inputs:
   pull_token:
@@ -92,21 +94,12 @@ runs:
     - name: Install pkg-config and openssl
       shell: bash
       run: |
-        if [[ "$RUNNER_OS" == "Linux" ]]; then
-          if ! dpkg -s pkg-config libssl-dev &> /dev/null; then
-            echo "pkg-config and/or libssl-dev not found. Installing..."
-            sudo apt-get update
-            sudo apt-get install -y pkg-config libssl-dev
-          else
-            echo "pkg-config and libssl-dev are already installed."
-          fi
-        elif [[ "$RUNNER_OS" == "macOS" ]]; then
-          if ! brew list | grep -E "pkg-config|openssl@3" &> /dev/null; then
-            echo "pkg-config and/or openssl not found. Installing..."
-            brew install pkg-config openssl@3
-          else
-            echo "pkg-config and openssl are already installed."
-          fi
+        if ! dpkg -s pkg-config libssl-dev &> /dev/null; then
+          echo "pkg-config and/or libssl-dev not found. Installing..."
+          sudo apt-get update
+          sudo apt-get install -y pkg-config libssl-dev
+        else
+          echo "pkg-config and libssl-dev are already installed."
         fi
       
     - name: Set up Docker
