updated example programs

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -4,7 +4,7 @@ SHELL := /bin/bash
 all:
 	@for dir in */ ; do \
 		echo "Building in $${dir}..."; \
-		cd $${dir} && cargo prove build || { echo "Failed at command: cd $${dir} && cargo build"; exit 1; }; \
+		cd $${dir} && cargo prove build || { echo "Failed at command: cd $${dir} && cargo prove build"; exit 1; }; \
 		cd ..; \
 	done
 
