stop modifying stuff outside of docker

diff --git a/.github/workflows/docker-gnark.yml b/.github/workflows/docker-gnark.yml
--- a/.github/workflows/docker-gnark.yml
+++ b/.github/workflows/docker-gnark.yml
@@ -48,3 +48,14 @@ jobs:
           command: test
           toolchain: 1.81.0
           args: --release -p sp1-prover -- --exact tests::test_e2e --nocapture
+
+      - name: Make sure the contracts were modified
+        run: |
+          if grep -q "pragma solidity ^0.8.0" ~/.sp1/circuits/dev/Groth16Verifier.sol; then
+            echo "Error: Groth16Verifier.sol still contains the old pragma version"
+            exit 1
+          fi
+          if grep -q "pragma solidity ^0.8.0" ~/.sp1/circuits/dev/PlonkVerifier.sol; then
+            echo "Error: PlonkVerifier.sol still contains the old pragma version"
+            exit 1
+          fi
