ci: run examples on merge to main

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,6 +39,7 @@ jobs:
         env:
           RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
           RUST_BACKTRACE: 1
+
   plonk-docker:
     name: Plonk Docker
     runs-on: runs-on,cpu=64,ram=256,family=m7i+m7a,hdd=80,image=ubuntu22-full-x64,spot=false
@@ -60,12 +61,47 @@ jobs:
         env:
           RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
           RUST_BACKTRACE: 1
-  check-branch:
-    name: Check branch
-    runs-on: ubuntu-latest
+
+  # check-branch:
+  #   name: Check branch
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check branch
+  #       if: github.head_ref != 'dev' && !startsWith(github.ref, 'release/') && !startsWith(github.ref, 'hotfix/')
+  #       run: |
+  #         echo "ERROR: You can only merge to main from dev, release/*, or hotfix/*."
+  #         exit 1
+
+  ssz-withdrawals:
+    name: Example (SSZ Withdrawals)
+    runs-on: runs-on,cpu=64,ram=256,family=m7i+m7a,hdd=80,image=ubuntu22-full-x64,spot=false
+    env:
+      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
     steps:
-      - name: Check branch
-        if: github.head_ref != 'dev' && !startsWith(github.ref, 'release/') && !startsWith(github.ref, 'hotfix/')
+      - name: Checkout sources
+        uses: actions/checkout@v4
+
+      - name: Setup CI
+        uses: ./.github/actions/setup
+
+      - name: Install SP1 toolchain
         run: |
-          echo "ERROR: You can only merge to main from dev, release/*, or hotfix/*."
-          exit 1
+          curl -L https://sp1.succinct.xyz | bash
+          ~/.sp1/bin/sp1up 
+          ~/.sp1/bin/cargo-prove prove --version
+
+      - name: Install SP1 CLI
+        run: |
+          cd cli
+          cargo install --force --locked --path .
+          cd ~
+
+      - name: Run script
+        run: |
+          cd examples/ssz-withdrawals
+          cargo add sp1-zkvm --path $GITHUB_WORKSPACE/zkvm/entrypoint
+          cargo prove build
+          cd ../script
+          cargo remove sp1-sdk
+          cargo add sp1-sdk --path $GITHUB_WORKSPACE/sdk
+          SP1_DEV=1 RUST_LOG=info cargo run --release
